title: HMX
author: dfmd
email: hmx@hangarmx.com
description: > # this means to ignore newlines until "show_excerpts:"
  Tienda en línea de productos maquinados en CNC,
  servicio de corte con router de control numérico e impresión 3D.

#Used for sitemap plugin
url: https://hangarmx.com
google_analytics: UA-151351771-1
#Used for local development
repository: dfmdmx/dfmdmx.store.io
#Used for post like structures
collections:
  products:
    output: true
  services:
    output: true
  groups:
    output: true
  landings:
    output: true
#Header menu activations
show_services: true
show_products: true

# Comments login
disqus:
  shortname: hangarmx
  comments: false

# Live chat active
tawk: true

# social links
email_username: hmx@hangarmx.com
twitter_username: _hangarmx
whatsapp_username: 'pending'
# facebook_username: hangarmx
instagram_username: _hangarmx
# flickr_username: jekyll
# github_username:  dfmdmx
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
#  - checkout.md
#  - software.md
#  - gallery.md
#  - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-github-metadata
